### ISSUE TITLE
Analyze - filter by severity

### ISSUE THREAD

**Issue by James-Osgood** [DeepCodeAI/cli#14]
It would be nice if the `analyze` command had an option to return only issues found at a specified severity ("Critical", "Warning", or "Info"). The exit code would also reflect issues found only at that severity.

This would be useful in automated pipelines to determine the scope of the issues DeepCode found. "Info" may require a less immediate response than "Critical". Some projects may only be interested in "Warning" and "Critical" issues.

There is already the option to skip/enable the linter-level issues. I think issue severity would be better served by a separate option. E.g. `deepcode analyze --severity=warning`.

**Comment by Arvi3d** [comment]
Hi James,
thank you for this request. 
Please consider upgrading to a newer version, 1.0.10, that has this new feature.

It looks exactly as you asked:
```bash
deepcode analyze --severity info|warning|critical
```
